# Generated by Django 5.1.4 on 2025-01-24 05:42

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Connection = apps.get_model('blog', 'Connection')
    for post in Post.objects.all():
        for category in post.categories.all():
            Connection(
                category=category,
                post=post,
                comment=''
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_name_connection'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]

